---
Project title: "Customer Behavioural Analytics in the Retail sector"
output:
  rmarkdown::html_document:
      toc: true
      toc_depth: 3  
      number_sections: false 
      theme: lumen  
      df_print: paged
      toc_float: 
        collapsed: true
        smooth_scroll: true 
    
 
---

<style>
body {
text-align: justify}
</style>

#Customer Behavioural Analytics in the Retail Sector


```{r echo=TRUE, message=FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(factoextra)
library("RColorBrewer")
library(cluster)
library("metricsgraphics")


# read file contents
supermarket_data_clean <- read.csv("Supermarket_DataCleaned.csv")

# Prepare data frames for clustering
#cloumns custoner_id, amount_purchased_shop_1, 2, 3, 4, 5
cluster.slice.temp <- supermarket_data_clean[,c(1,29,30,31,32,33)]
cluster.slice.data <- supermarket_data_clean[,c(29,30,31,32,33)]

# Scale the data and Determine the ideal number of clusters
cluster.slice.scale <- scale(cluster.slice.data)
cluster.slice.data.bot<-sample_frac(cluster.slice.data, 0.5)

wssplot <- function(data, nc=15, seed=1234){
  wss <- (nrow(data)-1)*sum(apply(data,2,var))
  for (i in 2:nc){
    set.seed(seed)
    wss[i] <- sum(kmeans(data, centers=i)$withinss)}
  plot(1:nc, wss, type="b", xlab="Number of Clusters",
       ylab="Within groups sum of squares")}

wssplot(cluster.slice.scale)

# The sharp decreases from 1 to 4 clusters with a little decrease between 4 to 5 estimates a 4 or 5 cluster solution
```

```{r echo=TRUE, message=FALSE}
#K-means clustering

set.seed(123) # fix the random starting clusters
kclust4 <- kmeans(cluster.slice.data, 4, nstart = 25)

set.seed(123) # fix the random starting clusters
kclust5 <- kmeans(cluster.slice.data, 5, nstart = 25)
```

```{r echo=TRUE, message=FALSE}
#PCA to visualize and verify the appropriate number of clusters
colours_shema <- c("Red", "Green", "Yellow", "Pink", "Blue", "Purple", "steelblue1", "tomato1")
cluster.pc <- prcomp(cluster.slice.data, center = FALSE, scale. = FALSE)$x %>% as.data.frame()
cluster.pc$kmeans.cluster <- factor(kclust4$cluster)

p<-ggplot(cluster.pc,aes(x=PC1,y=PC2,color=kmeans.cluster))
p+geom_point() +
  theme_bw() + scale_y_continuous(labels = scales::comma)



```

```{r echo=TRUE, message=FALSE}
#PCA to visualize and verify the appropriate number of clusters

cluster.pc1 <- prcomp(cluster.slice.data, center = FALSE, scale. = FALSE)$x %>% as.data.frame()
cluster.pc1$kmeans.cluster <- factor(kclust5$cluster)

p<-ggplot(cluster.pc1,aes(x=PC1,y=PC2,color=kmeans.cluster ))
p<-p+geom_point()
p
```

```{r echo=TRUE, message=FALSE}
#Comparing the PCA plots determine K-means 5 cluster solution, Hence clustering visualization with 5 clusters

fviz_cluster(kclust5, data = cluster.slice.data.bot, geom = "point",
             stand = FALSE, ellipse.type = "norm") + 
  ggtitle(label='Customer Clusters') 
```

