---
title: "RQ5"
author: "Sumit Kundu"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## EDA

__6. Visualize the revenue generated by each shop__ <br />

```{r echo=TRUE, message=FALSE}
## Call the packages
library(tidyverse)
library(ggplot2)
library("RColorBrewer")
library(plotly)

file_path <- "/home/sumit/Data-Science-with-R/Input Dataset/Cleaned Dataset/Supermarket_DataCleaned.csv"
supermarket_data_clean <- read_csv(file_path)

### Loyality Score based on Revenue ###

## Calculate the revenue generated for each shop
revenue_shop_1 <- sum(supermarket_data_clean$amount_purchased_shop_1)
revenue_shop_2 <- sum(supermarket_data_clean$amount_purchased_shop_2)
revenue_shop_3 <- sum(supermarket_data_clean$amount_purchased_shop_3)
revenue_shop_4 <- sum(supermarket_data_clean$amount_purchased_shop_4)
revenue_shop_5 <- sum(supermarket_data_clean$amount_purchased_shop_5)

## Create a vector 
revenue <- c(revenue_shop_1, revenue_shop_2, revenue_shop_3, revenue_shop_4, revenue_shop_5)
shops <- c("shop 1", "shop 2", "shop 3", "shop 4", "shop 5")

## Create a data frame to store the vectors
revenue_per_shop <- data.frame(shops, revenue)

## Generate a plot
rps_plot <- ggplot(revenue_per_shop, aes(shops, revenue))

## Add featurs to the plot
rps_plot + geom_bar(stat = "identity", width = 0.6, position = "dodge2") +
  xlab("Shops") + ylab("Revenue") +
  ggtitle("Revenue Generated") +
  theme_bw() + scale_y_continuous(labels = scales::comma)

```

_Analysis:_ The revenue generated by each shop can be calculated and used to generate a list of top n customers based on their contribution. Business can segment the list into multiple categories and formularize customized promotional offers for them. 